### ISSUE TITLE
concatenate on trailing dimensions

### ISSUE THREAD

**Issue by jennan** [DylanMuir/TensorStack#2]
At present time, TensorStack cannot concatenate on unitary trailing dimension. Example:

```
% this works
cat(4, ones(2, 1), ones(2, 1));
% this does not
TensorStack(4, ones(2, 1), ones(2, 1));
```

To address that, we would need to change `oStack.cvnTensorSizes` initialization in the constructor and maybe few other bits around.

**Comment by DylanMuir** [comment]
Enhancement incorporated in #1
